### ISSUE TITLE
Stack corruption filling in the world

### ISSUE THREAD

**Issue by Sargeanthost** [PryPurity/WorldBorder#14]
**Describe the bug**:
`[20:55:24 ERROR]: [global] TIMING_STACK_CORRUPTION - Look above this for any errors and report this to Paper unless it has a plugin in the stack trace (TimingIdentifier{id=Minecraft:world - World Save - Chunks} did not stopTiming)
[20:55:24 WARN]: [WorldBorder] Task #32965 for WorldBorder v2.0.9 generated an exception
java.lang.NullPointerException: null
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176) ~[?:?]
        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
        at net.minecraft.server.v1_16_R1.PlayerChunkMap.save(PlayerChunkMap.java:892) ~[Paper-1.16.1.jar:git-Paper-138]
        at net.minecraft.server.v1_16_R1.ChunkProviderServer.save(ChunkProviderServer.java:693) ~[Paper-1.16.1.jar:git-Paper-138]
        at net.minecraft.server.v1_16_R1.WorldServer.save(WorldServer.java:977) ~[Paper-1.16.1.jar:git-Paper-138]
        at org.bukkit.craftbukkit.v1_16_R1.CraftWorld.save(CraftWorld.java:1431) ~[Paper-1.16.1.jar:git-Paper-138]
        at com.wimbli.WorldBorder.WorldFillTask.reportProgress(WorldFillTask.java:441) ~[?:?]
        at com.wimbli.WorldBorder.WorldFillTask.run(WorldFillTask.java:225) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[Paper-1.16.1.jar:git-Paper-138]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[Paper-1.16.1.jar:git-Paper-138]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1298) ~[Paper-1.16.1.jar:git-Paper-138]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[Paper-1.16.1.jar:git-Paper-138]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[Paper-1.16.1.jar:git-Paper-138]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[Paper-1.16.1.jar:git-Paper-138]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[Paper-1.16.1.jar:git-Paper-138]
        at java.lang.Thread.run(Thread.java:834) [?:?]`
**Server Version**:
paper-1.16.1-latest
**Plugin Version**:
Latest
**Plugins**:
`Disenchanted-2.0-SNAPSHOT.jar    EssentialsXSpawn-2.18.1.0.jar  Vault.jar
AntiCooldown.jar  EssentialsX-2.18.1.0.jar         Item2Chat-4.2.3.jar            ProtocolLib.jar          VeinMiner-1.16.1.jar
EssentialsXChat-2.18.1.0.jar     Spigot-CommandSigns.jar  
EssentialsXProtect-2.18.1.0.jar  LuckPerms-Bukkit-5.1.93.jar    WorldBorder.jar`

**Comment by Sargeanthost** [comment]
Version 2.0.9 failed once again while generating on paper. I thought this issue was fixed due to #2 , but I guess not. Reopening.

**Comment by PryPurity** [comment]
Is your world being imported from a version before 1.15/1.16?

Also, I will need the full log.
