### ISSUE TITLE
Update for 1.16.1 Please - Errors Included

### ISSUE THREAD

**Issue by Goonhaven** [PryPurity/WorldBorder#4]
Hi, I believe this is a 1.16.1 error. It occurs when using /wb fill 1000 then /wb fill confirm:

```
[WorldBorder] Task #67 for WorldBorder v2.0.4 generated an exception
java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	at com.wimbli.WorldBorder.WorldFileData.getRegionData(WorldFileData.java:174) ~[?:?]
	at com.wimbli.WorldBorder.WorldFileData.doesChunkExist(WorldFileData.java:108) ~[?:?]
	at com.wimbli.WorldBorder.WorldFileData.isChunkFullyGenerated(WorldFileData.java:119) ~[?:?]
	at com.wimbli.WorldBorder.WorldFillTask.run(WorldFillTask.java:243) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.1.jar:git-Spigot-758abbe-38de0b8]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot-1.16.1.jar:git-Spigot-758abbe-38de0b8]
	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1059) ~[spigot-1.16.1.jar:git-Spigot-758abbe-38de0b8]
	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:354) ~[spigot-1.16.1.jar:git-Spigot-758abbe-38de0b8]
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1007) ~[spigot-1.16.1.jar:git-Spigot-758abbe-38de0b8]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:846) ~[spigot-1.16.1.jar:git-Spigot-758abbe-38de0b8]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.1.jar:git-Spigot-758abbe-38de0b8]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

**Comment by PryPurity** [comment]
Please use the correct bug report format. Also this was fixed in 2.0.5
